# This workflow will rebase legacy-projects branch on new pushes to main

name: Rebase branch legacy-projects

on:
  push: 
    branches: [ main ]

  workflow_dispatch:

jobs:
  rebase:
    name: Checkout legacy-projects and rebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        

      - name: Automatic Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          USER_NAME: fermoya
          USER_EMAIL: fmdr.ct@gmail.com
          OUTDATED_BRANCH: legacy-projects
          BASE_BRANCH: main
        run: ./scripts/rebase.sh
